"""New Migration

Revision ID: 8ff6dc92570a
Revises: a3ccd0fa72fe
Create Date: 2023-05-24 11:54:13.120837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff6dc92570a'
down_revision = 'a3ccd0fa72fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
