"""New Migration

Revision ID: 9abfe14c64fe
Revises: f4cce0bf2683
Create Date: 2023-05-24 12:18:01.061417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abfe14c64fe'
down_revision = 'f4cce0bf2683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
