"""New Migration

Revision ID: f4cce0bf2683
Revises: 8ff6dc92570a
Create Date: 2023-05-24 12:12:39.439693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cce0bf2683'
down_revision = '8ff6dc92570a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
